### PR TITLE
Set GB_CLI_TIMEOUT value as part of container startup.

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
> Please describe the need for this change in the commit message. Point to public bugs if they exist.

Done

**Comment by nixpanic** [comment]
Now this confuses me. The commit message mentions that gluster-block uses `/etc/sysconfig/gluster-blockd`, but the environment is changed/added to `/usr/lib/systemd/system/gluster-blockd.service`. Changing the option in `/etc/sysconfig/gluster-blockd` would be much cleaner.

What is the reason to change the default of 900 to 600? Or is the 900 in the commit message just an example?

**Comment by SaravanaStorageNetwork** [comment]
> Now this confuses me. The commit message mentions that gluster-block uses `/etc/sysconfig/gluster-blockd`, but the environment is changed/added to `/usr/lib/systemd/system/gluster-blockd.service`. Changing the option in `/etc/sysconfig/gluster-blockd` would be much cleaner.

Nope, the value is updated in gluster-blockd.service file only. 
I have referred the bz for updating this comment. and hence the confusion. I will reword it. 

> What is the reason to change the default of 900 to 600? Or is the 900 in the commit message just an example?

Yes, 900 is just and example.  I will better reword this one too  to avoid confusion.

**Comment by SaravanaStorageNetwork** [comment]
> Changing the option in `/etc/sysconfig/gluster-blockd` would be much cleaner.

Agree. But even another variable is updated in gluster-blockd.service only. 
I will take up this cleanup of moving to /etc/sysconfig/gluster-blockd separately. 

Ref: https://github.com/gluster/gluster-containers/blob/master/CentOS/update-params.sh#L37

**Comment by humblec** [comment]
@SaravanaStorageNetwork anything pending here ?

**Comment by SaravanaStorageNetwork** [comment]
> @SaravanaStorageNetwork anything pending here ?

All done.

**Comment by humblec** [comment]
LGTM. Merging! Thanks all!

**Pull request merged**
