### PR TITLE
Travis CI update and disabling dockerfile_lint

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Travis now runs the test where it:

* Builds the Dockerfile

* Runs Docker image with required parameters

* Verifies the state of the container

Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
@humblec Travis fixed with this PR.

**Comment by MohamedAshiqrh** [comment]
@gluster/container-storage-admin Travis fixed.

**Comment by MohamedAshiqrh** [comment]
@humblec PTAL

**Comment by humblec** [comment]
LGTM. Merging.

**Pull request merged**
