### PR TITLE
Cleaning up RUN in dockerfile

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
This reduces the image size as it reduces the number of intermediate layers.

Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
@humblec PTAL

This reduced 10MB from image size.

Actual image 312MB. 
This image 292MB.

**Comment by MohamedAshiqrh** [comment]
192MB is the centos image size. With gluster installed and little configurations changed it comes upto 312MB size. Let me see if there are other ways to decrease image size.

**Comment by humblec** [comment]
@MohamedAshiqrh Travis is failing

**Comment by MohamedAshiqrh** [comment]
@humblec travis failing on npm dependency. I am trying to fix it. But tests are passing locally.

**Comment by MohamedAshiqrh** [comment]
@humblec We can wait till travis CI is fixed and then merge this.

**Comment by MohamedAshiqrh** [comment]
```
$ sudo npm install -g dockerfile_lint

npm WARN npm npm does not support Node.js v0.10.37

npm WARN npm You should probably upgrade to a newer version of node as we

npm WARN npm can't make any promises that npm will work with this version.

npm WARN npm You can find the latest version at https://nodejs.org/

npm ERR! Object function (err) {

npm ERR!         if (err) return cb(err)

npm ERR!         fs.fsync(fd, function (err) {

npm ERR!           if (err) return cb(err)

npm ERR!           fs.close(fd, cb)

npm ERR!         })

npm ERR!       } has no method 'toLowerCase'


```

I fixed this one but ended up in one more dependency failure. looks like dependency is broken.

I am not able to build it.

**Comment by MohamedAshiqrh** [comment]
I am rewriting the CI.

**Comment by MohamedAshiqrh** [comment]
@humblec PTAL
@prashanthpai can you take a look at swift image?

This is mainly to reduce the intermediate layers and thereby reduce the image size.

**Comment by MohamedAshiqrh** [comment]
@prashanthpai Thanks.

@humblec can you please review this?

**Comment by humblec** [comment]
LGTM. Merging.

**Pull request merged**
