### PR TITLE
Centos Dockerfile for Gluster4.0

### PR DESCRIPTION
**Pull request by Madhu-1**
updated author name in Dockerfile for
Gluster4.0 release

Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@Madhu-1 it need update in different places :)
https://github.com/gluster/gluster-containers/blob/master/CentOS/Dockerfile#L9
 https://github.com/gluster/gluster-containers/blob/master/CentOS/Dockerfile#L17

**Comment by Madhu-1** [comment]
@humblec , updated Gluster version

**Comment by humblec** [comment]
I dont see the centos release rpm name change in the PR.

**Comment by Madhu-1** [comment]
@humblec updated rpm name

**Comment by humblec** [comment]
@Madhu-1 we need changes in the README about this, replace v3.11 entries with v4.0

**Pull request merged**
