### PR TITLE
Rename as s3 

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
rename docker-gluster-swift as docker-gluster-s3

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
Can you squash the commits? @SaravanaStorageNetwork

**Comment by MohamedAshiqrh** [comment]
Is the main README also renamed?

**Comment by humblec** [comment]
@SaravanaStorageNetwork Can you resolve this conflict?

**Comment by SaravanaStorageNetwork** [comment]
Adding a new one as this is messed up - https://github.com/gluster/gluster-containers/pull/48

**Pull request closed without merging**
