### PR TITLE
Add gluster-block to the gluster image

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
@humblec gluster-block package I am not able to find.

**Comment by humblec** [comment]
@MohamedAshiqrh its in copr repo. ping Prasanna he can give the exact url.

**Comment by MohamedAshiqrh** [comment]
https://download.gluster.org/pub/gluster/gluster-block/LATEST/fedora/25/x86_64/ is the latest I could find and I don't think it will have the fixes that we require. have sent a mail, will wait for the response.

**Comment by jl-dos** [comment]
@MohamedAshiqrh Any update on this PR? Curious as it would be helpful to have gluster-block in the image being used with Kubernetes. Currently heketi cannot provision block claims without.

**Comment by lentzi90** [comment]
This should be simple to fix now when `centos-release-gluster40` is used, as it provides gluster-block.
Just add `yum --setopt=tsflags=nodocs -y install gluster-block` and `systemctl enable gluster-blockd.service`.

Can someone update this pull request?

**Comment by mtoddw** [comment]
any update on this issue? I'm still unable to provision block pvcs?

**Comment by humblec** [comment]
@mtoddw @jl-dos ideally this should be already fixed in master and `4.x` branches. For the same reason, I am closing this PR.  Please feel free to open an issue if there is a question/issue.

**Pull request closed without merging**
