### PR TITLE
Update gluster version

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
Update glusterfs version to 4.0 (from 3.13).
    
    3.13 is EOL'd - refer: https://www.gluster.org/release-schedule

### CODE REVIEW

**Comment by humblec** [comment]
@SaravanaStorageNetwork true., its EOLd on end of March 2018. But I think we can still have the container available in docker hub, why dont you send a NEW pr for 4.0 ?  I am creating a branch for 4.0 and making current master to 3.13. You can send it against 4.0.

**Comment by humblec** [comment]
Discard my last comment, we already have these branches in place and also the dockerfile has been available for 4.0 https://github.com/gluster/gluster-containers/commit/75b59b99577b7a9b79e224a376f29fa0985fb52e

**Comment by SaravanaStorageNetwork** [comment]
@humblec 
So, shouldn't we make 4.0 branch as master then ? 

If anyone tries to build docker container out of master branch(with 3.13) it will fail.
So, all PRs posted in master branch will be keep failing in CI. (with 3.13)

If glusterfs-3.13 is EOL'd so is the corresponding docker container too, correct ?

**Comment by humblec** [comment]
@SaravanaStorageNetwork u r correct, now we can do the switch , that branch was created before release or when 4.0 was in experiment. I will rename the branch to master.

**Pull request merged**
