### PR TITLE
Fedora: Update per Fedora container review

### PR DESCRIPTION
**Pull request by jarrpa**
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by jasonbrooks** [comment]
For fedora packaging purposes, it'd be better if the README.md included the info that's in the README in the dir above this one

**Comment by jarrpa** [comment]
@jasonbrooks Branch updated to reflect that change.

**Comment by jasonbrooks** [comment]
@jarrpa docker build doesn't like it `Forbidden path outside the build context: ../README.md ()`

**Comment by jarrpa** [comment]
@jasonbrooks ...crap. I'd really rather not duplicate content like that, is there any alternative, like a URL to the repo's main README somewhere? Or heck, just do an ADD with said URL?

**Comment by jasonbrooks** [comment]
@jarrpa I guess an url would do

**Comment by jasonbrooks** [comment]
I mean, put the url to the parent readme in the image's readme -- I'm not sure if ADD by url works?

**Comment by jarrpa** [comment]
It does! One of the key differences between ADD and COPY is that ADD can parse URLs whereas COPY cannot. Patches updated.

**Comment by jasonbrooks** [comment]
OK, LGTM

**Comment by nixpanic** [comment]
Merged because @jarrpa is a maintainer for the container, and Humble is unavailable this week. Reviewed by Jason (and myself FWIW).

**Pull request merged**
